logging:
   level:
      org:
         springframework: INFO
# Ehcache configuration.
spring:
   cache:
      ehcache:
         config: classpath:ehcache.xml
         names: productCache
         type: ehcache
   jpa:
      properties:
         hibernate:
            show_sql: true
            format_sql: true